services:
  api:
    container_name: ml_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - shared_network

  model:
    container_name: ml_model
    build:
      context: ./model
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # Mount data directory for datasets
    networks:
      - shared_network

  ui:
    container_name: web
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - redis
      - node_redis
    networks:
      - shared_network
  node_redis: 
    container_name: node_redis
    build: 
      context: ./ui/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared_network
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - shared_network
  test:
    container_name: test
    build:
      context: ./test
      dockerfile: Dockerfile
    networks:
      - shared_network
    depends_on:
      - redis
networks:
  shared_network:
    external: true
    name: shared_network
